[iv22_medium] Support all watches with AMOLED screens
The following models are now supported:

- [390 x 390] Approach S70 42mm
- [454 x 454] Approach S70 47mm
- [416 x 416] D2 Mach 1
- [416 x 416] epix (Gen 2)
- [390 x 390] epix PRO (Gen 2) 42mm
- [416 x 416] epix PRO (Gen 2) 47mm
- [454 x 454] epix PRO (Gen 2) 51mm
- [416 x 416] Forerunner 265
- [360 x 360] Forerunner 265s
- [454 x 454] Forerunner 965
- [390 x 390] MARQ (Gen 2) Athlete / Adventurer / Captain / Golfer
- [390 x 390] MARQ (Gen 2) Aviator
- [416 x 416] Venu 2
- [416 x 416] Venu 2 Plus
- [360 x 360] Venu 2S

venusq2 and venusq2m are not supported because of:
```
Error: Symbol Not Found Error
Details: Could not find symbol 'setFill'
Stack:
  - <globals/IV22MView/<>initMaskLayer>() at ./garmin-watchfaces/iv22_medium/source/IV22MView.mc:40 0x100006b6
  - onUpdate() at ./garmin-watchfaces/iv22_medium/source/IV22MView.mc:98 0x10000743

Encountered app crash.
```